services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:bullseye
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
    depends_on:
      - db
      - redis

  db:
    image: postgres:17-bullseye
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo

  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redis-data:/data
    network_mode: service:db

volumes:
  postgres-data:
  redis-data:
